# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f662aa373d8b1767b59c8ffad22fe74d622540a22810f259789067f3e5f39d5e4612704a8e72a458a1de785f1da2407ec3b16aafa6069b77144734f4eac5f8a7

test:
  secret_key_base: 740daca10c00729a860f9ccffdda1bf95146a12555c591b5cbdd8f86b317ec2bc5543bdad857829223f9476fb6bdc762e6b5bc4668a6dbee04d3fc39b8c90a84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
